import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
import "@styles/globals.css";
import ReactQueryProvider from "@/api/instances/reactQuery/react-query";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <ReactQueryProvider>
            {process.env.NODE_ENV === 'development' && (<ReactQueryDevtools initialIsOpen={false} />)}
            <div className="w-[363px] h-screen">
              {children}
          </div>
          </ReactQueryProvider>
        </body>
    </html>
  );
}
